import praw
from dhooks import Webhook, Embed
import json

reddit = praw.Reddit(#Reddit stuff)

subreddit = reddit.subreddit('deepfriedmemes')

emojis = [
    "🆔",
    "🅰",
    "🅱",
    "🆎",
    "🆑",
    "🅾",
    "🆘",
    "🆚",
    "🆖",
    "🆗",
    "🅿",
    "🐝",
    "㊗",
    "🈴",
    "🈵",
    "🈲",
    "㊙",
    "🉑",
    "🈲",
    "🈵",
    "🉐",
    "🈹",
    "㊙️",
    "🈸",
    "🈺",
    "🈷️",
    "🈚️",
    "💮"]
upvote_asking = ["likes", "votes", "vote"]

upvote_removal = ["upvote", "downvote", "updoot"]

sleeping_mods = [
    "mods are asleep",
    "mods are sleeping",
    "mods aren\'t awake",
    "mods be sleepin\'",
    "mods be sleepin"]

hook = Webhook("WEbhook link")
reported_posts = "**Reported posts**: \n \n -"


mod_list = {
    #Privacy
}


reason = {
    "Repost": "1) NO reposts. Offenders will be banned. Repeated offenders will be permabanned. If you intend on posting something, make sure that it has not already been posted here. We recommend that you don\'t ...",
    "Asking for Upvotes": "2) Posts asking for upvotes in the title and/or in the meme is not allowed.",
    "No text": "3) Pictures with text are better. Straight up pictures with a filter will LIKELY be removed.",
    "Punchline in the title": "4) Don\'t put the punchline in title. The meme must hold its own.",
    "No politics": "5) This is not a place for politics. Political memes are not welcome here.",
    "/u/DeepFryBot Post": "6) Posting memes generated by /u/DeepFryBot is a bannable offense. DON\'T EVEN TRY, MATE.",
    "Lazily Fried": "7) Memes that can be considered lightly/lazily fried or nuked may be removed. You shouldn\'t just add one filter of noise, but you shouldn\'t add 10,000 filters of everything either. This is /r/DeepFriedMemes, not r/sauteedmemes or /r/nukedmemes. We shouldn\'t have to say this since it\'s so obvious but completely raw memes are not allowed either.",
    "Rule 7B: No nuked memes": "7) Memes that can be considered lightly/lazily fried or nuked may be removed. You shouldn\'t just add one filter of noise, but you shouldn\'t add 10,000 filters of everything either. This is /r/DeepFriedMemes, not r/sauteedmemes or /r/nukedmemes. We shouldn\'t have to say this since it\'s so obvious but completely raw memes are not allowed either.",
    "Raw": "9) Do not post raw memes asking people to fry them for you. There\'s /r/FryMyMeme for that. Learning how to fry is not particularly hard, there are many easy to follow guides.",
    "Edgy": "10) Edgy memes are not allowed and will be removed. There are very obvious lines that shouldn\'t be crossed. This includes (but is not limited to) jokes about pedophilia/child exploitation, rape, incest, terrorist attacks, school shootings, sexual assault, and bombings. Don\'t make memes out of tragic events on the day it happens, have some respect.",
    "Shitpost": "Mods reserve themselves the right to remove/approve content they want even if it doesn't explicitly break/conform to a rule. \n Posts that the mods decide to remove that don\'t explicitly break any rules will be flaired as Shitpost. Message the mods to ask why your post was removed if you have a post removed as a shitpost. ",
    "B": "We have decided to ban the B-emoji and similar [See here: https://old.reddit.com/r/DeepFriedMemes/comments/ajszxq/a_revision_on_banning/ ]"
}


def taken_action():
    # As simple as it implies to be
    global action_taken
    with open("action.json", "r") as fp:
        action_taken = json.load(fp)
    action_taken = action_taken + 1
    with open("action.json", "w") as fp:
        json.dump(action_taken, fp)


def discord_webhook(del_link, x, type, length):
    if x == "c":
        # Comment
        comment = del_link
        if len(comment.body) > 2000:
            desc = "**Message too long**"
        else:
            desc = comment.body
        embed = Embed(
            description=str(desc),
            color=0xff242b)
        embed.add_field(
            name='Permalink:',
            value=f"https://reddit.com{str(comment.permalink)}")

    elif x == "s":
        submission = del_link
        embed = Embed(
            description=str(submission.title),
            color=0xfc14ff
        )
        embed.add_field(
            name='Permalink:',
            value=f"https://reddit.com{str(submission.permalink)}")

    embed.set_author(
        name=type,
        icon_url="https://cdn.discordapp.com/emojis/479560571478343700.png?v=1")

    embed.add_field(name='Number:', value=str(action_taken))
    embed.set_footer(
        text='Prepare for the modmail!',
        icon_url="https://cdn.discordapp.com/emojis/531054128823140362.png?v=1")

    if length > 0:
        embed.add_field(name="Ban Length:", value=str(length))
    elif isinstance(length, str):
        embed.add_field(name="Note:", value=length)
    try:
        hook.send(embed=embed)
    except BaseException:
        print("Error in Webhook!")


def submission_r(submission, x):
    if x in reason:
        x = reason[x]

    submission.reply(f"Hello /u/{str(submission.author)}, thanks for posting to /r/DeepFriedMemes. Unfortunately your post has been removed for the following reason(s): \n \n"
                     f"- {str(x)} \n \n \n *If you feel that your post was removed in error or are unsure about why this post was removed then please contact us through [modmail](https://www.reddit.com/message/compose?to=%\2Fr%\2FDeepFriedMemes).* \n \n \n I\'m a bot created to make modding easier for everyone! - This is action {str(action_taken)} since the last restart!").mod.distinguish(how="yes", sticky=True)

    submission.mod.lock()
    submission.mod.remove()

def ban(submission, reason, length):
    reddit.subreddit('deepfriedmemes').banned.add(
        submission.author,
        ban_reason=reason,
        duration=str(length),
        ban_message=reason)
